export const REGISTER_ACCOUNT = "/api/auth/register"
export const CREATE_TIMESLOT = "/api/appointment/timeslot/create"
export const DELETE_TIMESLOT = "/api/appointment/timeslot/delete"
export const FETCH_ALL_TIMESLOT = "/api/appointment/timeslot/fetch-all"
export const FETCH_ALL_DOCTOR_APPOINTMENTS = "/api/appointment/doctor/fetch-all"
export const FETCH_ALL_PATIENT_APPOINTMENTS = "/api/appointment/patient/fetch-all"
export const FETCH_ALL_DOCTOR_QUEUES = "/api/queue/fetch-all"
export const UPDATE_QUEUE_STATUS = "/api/queue/change-status"
export const CONFIRM_QUEUE = "/api/queue/confirm"
export const REMOVE_QUEUE = "/api/queue/remove"
export const ADD_QUEUE = "/api/queue/add"
export const COMPLETE_APPOINTMENT = "/api/appointment/complete"
export const COMPLETE_QUEUE = "/api/queue/complete"
export const CONFIRM_PAYMENT_APPOINTMENT = "/api/appointment/confirm-payment"
export const CONFIRM_APPOINTMENT = "/api/appointment/confirm-appointment"
export const CANCEL_PAYMENT_APPOINTMENT = "/api/appointment/cancel"
export const RESCHEDULE_APPOINTMENT = "/api/appointment/reschedule"
export const RESCHEDULE_APPOINTMENT_PATIENT = "/api/appointment/patient/reschedule"

export const FETCH_ALL_DOCTOR_INVOICES = "/api/invoice/doctor/fetch-all"
export const FETCH_ALL_NOTIFICATIONS = "/api/notification/fetch-all"
export const CLEAR_NOTIFICATIONS = "/api/notification/clear"
export const UPDATE_PROFILE = "/api/settings/profile"
export const UPDATE_PASSWORD = "/api/settings/password"
export const UPDATE_DISABLED_USER = "/api/settings/disable"

export const FETCH_ANALYTICS_DOCTOR = "/api/analytics/doctor"
export const FETCH_SEARCH_DOCTORS = "/api/search/doctors"
export const FETCH_SEARCH_SINGLE_DOCTOR = "/api/search/doctors/single"
export const BOOK_APPOINTMENT = "/api/appointment/book"

